PIP-1440-madQC
ENCODE-DCC/accession pull request #151
Opened 2020-11-05 12:26 UTC by ottojolanki

2020-11-05 16:18 UTC, paul-sud requested changes
One comment, otherwise looks good.

2020-11-05 16:18 UTC, paul-sud commented on accession/accession.py
> +            return
`self.experiment.get_number_of_biological_replicates()` is called three times. Would be good to consolidate:
```suggestion
        if encode_file.has_qc("MadQualityMetric"):
            return
           
        num_biological_replicates = self.experiment.get_number_of_biological_replicates()
        if num_biological_replicates > 2:
            return
        elif (
            num_biological_replicates == 1
            and self.experiment.get_number_of_technical_replicates() == 2
        ) or num_biological_replicates == 2:
            mad_qc = self.prepare_mad_qc_metric(gs_file)
            return self.queue_qc(mad_qc, encode_file, "mad-quality-metric", shared=True)
        else:
            return
```

2020-11-06 08:34 UTC, ottojolanki commented on accession/accession.py
> +            return
Yeah, considered this and decided that three dict accesses is better than extra variable :) I'm ok, with either way.

2020-11-06 16:21 UTC, paul-sud commented
@ottojolanki could you lint and re-push? Will merge once tests pass.

2020-11-10 18:36 UTC, merged