PIP-1444-local-accessioning
ENCODE-DCC/accession pull request #156
Opened 2020-11-16 21:48 UTC by paul-sud

2020-11-23 21:45 UTC, paul-sud commented
@ottojolanki this lays the foundation for local accessioning. To accomplish I did some refactoring around files, blobs, and backends. Previously the notion of file (mostly for holding file and relevant WDL metadata), and blob (for reading data) was separate, but now they have been merged together. Methods for reading files are now associated with the files and not the backend, so now you can do things like `qc = file.read_json()`. The old and confusingly named `Backend.read_file` is now `File.read_bytes`.

The backends are now very minimal and pretty much just generate the instances of the appropriate `File` subclass via `Backend.make_file`. I didn't completely get rid of the backends because for Google Cloud it is useful for the GSFile instances to share the same GCS client, so there still needs to be some coordination instantiating them.

2020-11-24 10:18 UTC, ottojolanki requested changes
This refactoring is a huge step into the right direction. Makes so much more sense to have lot of the functionality in Files rather than in Backends. Mostly cosmetic changes requested.

2020-11-24 10:18 UTC, ottojolanki commented on accession/backends.py
> +        alone for local files.
I suppose we could call `os.stat` on the path to see if the file exists?

2020-11-24 10:18 UTC, ottojolanki commented on accession/file.py
> +    def get_task_or_error(self) -> Task:
I think this could be just `get_task`. I feel like `_or_error` is sort of redundant.

2020-11-24 10:18 UTC, ottojolanki commented on accession/file.py
> +        Largely split into separate method for testability. Mocking super() is either
I don't think there is any need to explain why you are making small methods! Everyone loves small methods.

2020-11-24 10:18 UTC, ottojolanki commented on accession/file.py
> +        return self.blob.download_as_string()
This combination does not feel right. Is there some case where `A` (boto client) might read few bytes, and pause, and meanwhile `B` would read the whole file, and then `A` would resume?

2020-11-24 10:18 UTC, ottojolanki commented on accession/accession.py
>          bucket = path_parts.pop(0)
Not part of the diff, but figured I'll mention this now that it caught my eye. I think there are a few places where we could make the code better by thinking in terms of trying to have only objects of one level of abstraction in a method when possible. Maybe at some round of refactoring it might make sense to extract a small `URI` class that could hide this sort of path manipulations from the main accession class?

2020-11-24 10:18 UTC, ottojolanki commented on accession/accession.py
> +        file_name = file.get_uri_without_scheme().replace("/", "-")
Perhaps it would be good idea to add `get_filename_for_encode_alias` method into the `File` classes, in order to avoid low level string manipulations being visible here?

2020-11-24 17:31 UTC, paul-sud commented on accession/file.py
> +        return self.blob.download_as_string()
`read` only exists for s3 upload and isn't intended for use within accessioning code. The boto client does read in chunks but `read_bytes` won't be called in between `read` calls.

2020-11-24 18:05 UTC, paul-sud commented on accession/backends.py
> +        alone for local files.
I thought about it but I don't think its super necessary.

2020-11-24 18:10 UTC, paul-sud commented on accession/file.py
> +    def get_task_or_error(self) -> Task:
I just wanted to make it abundantly clear that using the method will cause an error if the file doesn't have a task, for instance for fastqs, but yeah it might be a little excessive. In the future I'll probably add more functions like this that unwrap `Optional` types and replace functions like this with something more generic.

2020-11-24 18:11 UTC, paul-sud commented on accession/backends.py
> +        alone for local files.
You will get other failures later getting `md5sum` or `size`

2020-11-24 18:13 UTC, paul-sud commented on accession/accession.py
>          bucket = path_parts.pop(0)
Haha I did think about adding classes for the different URIs but for some reason decided against it for this PR. Definitely a good idea for future improvement.

2020-11-24 18:22 UTC, paul-sud commented on accession/accession.py
> +        file_name = file.get_uri_without_scheme().replace("/", "-")
Yeah that's a good idea. I'll add it in.

2020-11-24 18:23 UTC, paul-sud commented on accession/file.py
> +    def get_task_or_error(self) -> Task:
Anyway if you don't think you need the `_or_error` then I will drop it.

2020-11-24 18:26 UTC, paul-sud commented on accession/file.py
> +        Largely split into separate method for testability. Mocking super() is either
The comment is actually irrelevant with the refactor. Composition over inheritance ftw.

2020-11-24 18:52 UTC, merged

2020-11-25 09:57 UTC, ottojolanki commented on accession/file.py
> +    def get_task_or_error(self) -> Task:
Not a big deal.