PIP-1598-pbam-bulk-rna
ENCODE-DCC/accession pull request #225
Opened 2021-08-06 17:57 UTC by ottojolanki

2021-08-06 19:37 UTC, paul-sud requested changes
One change requested. Also will need to use the new step versions with `ptools-bin` included.

One general comment - if you think it's useful, there is a feature that avoids posting the GCS URIs for the files and also doesn't post the metadata JSON as analysis attachment. We do it for ChIP pbam, it's set by passing `private_filenames=True` to `Accession` constructor. It does require complicating the accession factory though.

2021-08-06 19:37 UTC, paul-sud commented on accession/accession.py
> +        ],
It is a mutable default argument. Does this really need to be exposed as an argument? Could maybe just put it in the body of the function.

2021-08-06 19:37 UTC, paul-sud commented on accession/accession.py
> +        ],
Otherwise could just make it a tuple.

2021-08-09 17:27 UTC, ottojolanki commented on accession/accession.py
> +        ],
yeah, that makes sense.

2021-08-09 17:47 UTC, paul-sud approved these changes
LGTM

2021-08-20 19:25 UTC, merged